image_finetune: false

output_dir: "outputs/WebVid-test"
pretrained_model_path: "models/StableDiffusion/zerodiffusion-v0-9"

unet_additional_kwargs:
  use_inflated_groupnorm         : true
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_mid_block: true
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps:     1000
  beta_start:              0.00085
  beta_end:                0.012
  beta_schedule:           "scaled_linear"
  steps_offset:            1
  clip_sample:             false
  # Following settings will change for zero SNR training.
  prediction_type:         "v_prediction" # Default: "epsilon", ZSNR: "v_prediction"
  timestep_spacing:        "trailing" # Default: "leading", ZSNR: "trailing"
  rescale_betas_zero_snr:  true     # Default: false,     ZSNR: true

train_data:
  csv_path:        "/mnt/foxhole/webvid_clean/results_2M_train.csv"
  video_folder:    "/mnt/foxhole/webvid_clean"
  sample_size:     512
  sample_stride:   4
  sample_n_frames: 16

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christmas tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Two people walking down the street during a rainstorm."
    - "Pacific coast, carmel by the sea ocean and waves."
    - "A robot dancing in a park"
    - "Formula One racecar driving across finish line"
    - "Blonde female model, white shirt, white pants, white background, studio"
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."

# unet_checkpoint_path: "/mnt/sonic/AnimateDiff/models/Motion_Module/mm_sd_v15_v2.ckpt"
unet_checkpoint_path: "/mnt/sonic/AnimateDiff/ZeroDiffusion-Animate-RC1-LayerStrip.ckpt"

learning_rate:     1.0 # 5.e-5
lr_scheduler:      "constant_with_warmup"
lr_warmup_steps:   0
adam_weight_decay: 1.e-2
scale_lr: false
train_batch_size: 2
gradient_accumulation_steps: 64
use_torch_compile: false # Compiling is slow or impossible with gradient checkpointing
min_snr_gamma: 5
ip_noise_gamma: 0.1
channels_last: false
rescale_cfg: 0.0

# b1 channels last: 12.85 s/it
# b1 no channels last: 10.46 s/it

gradient_checkpointing: true

max_train_epoch:      -1
max_train_steps:      51200
checkpointing_epochs: -1
checkpointing_steps:  12800
wandb_scale_factor:   2

validation_steps:       1024
validation_steps_tuple: [128, 512]

# validation_steps:       20480
# validation_steps_tuple: [2048, 10240]

global_seed: 42
mixed_precision_training: "fp16"
enable_xformers_memory_efficient_attention: false # will fall back to SDP, don't worry

is_debug: false
do_profile: false